v2_1/ws/rest/docs/4_8_errors.md
=> Document "informational" status codes

v2_1/ws/rest/docs/4_6_conneg.md
=> Added media types for JSON & CSV

v2_1/ws/rest/docs/4_3_structural_queries.md, v2_1/ws/rest/src/sdmx-rest.wadl
=> Support Retrieval of Content Constraints by Type

v2_1/ws/rest/docs/4_7_errors.md, v2_1/ws/rest/src/sdmx-rest.wadl
=> Changed HTTP status code for SDMX error #150

v2_1/ws/rest/docs/4_6_conneg.md
Dear all,
Could you please review? It's part of v1.4.0, i.e. the version that will be released along with the VTL.
Thanks!
=> Added media-type for JSON structures

v2_1/ws/rest/src/sdmx-rest.yaml
510 is an SDMX code, not an HTTP one. SDMX 510 is mapped to HTTP 413, which is already documented.
=> Remove erroneous error code

v2_1/ws/rest/docs/4_3_structural_queries.md, v2_1/ws/rest/src/sdmx-rest.yaml
Just as reminder, this branch still needs to be merged with v1.5.0.
@stratosn, please let me know when you have the final list of resources.
=> VTL artefacts

v2_1/ws/rest/docs/4_3_structural_queries.md
=> Add AgencyScheme as reference to be returned

v2_1/ws/rest/docs/4_6_conneg.md
=> Add parameters to SDMX-CSV media type

v2_1/ws/rest/docs/4_3_structural_queries.md
Fix #85 
Re. CR-85: The Swagger definition had already been updated but not the documentation. Could you please review? Thanks!
=> Modify doc after structure grouping

v2_1/ws/rest/docs/4_7_errors.md
Resolves #84
Please also see the *Be liberal in what you accept section* on the [Wiki](https://github.com/sdmx-twg/sdmx-rest/wiki/Tips-for-providers#be-liberal-in-what-you-accept).
=> Behaviour in case of mixed semantically valid and invalid requests

v2_1/ws/rest/docs/4_5_schema_queries.md, v2_1/ws/rest/docs/4_6_conneg.md, v2_1/ws/rest/src/sdmx-rest.yaml
=> Mime types for schema queries

v2_1/ws/rest/docs/4_1_introduction.md, v2_1/ws/rest/docs/4_2_scope.md, v2_1/ws/rest/docs/4_3_structural_queries.md, v2_1/ws/rest/docs/4_5_schema_queries.md
Dear all,
Another PR, this time focusing on the agreement around operators.
The data page has not changed in this PR, because the necessary changes have been made in [another PR](https://github.com/sdmx-twg/sdmx-rest/pull/124).
Cheers,
Xavier
=> Harmonize use of operators

v2_1/ws/rest/docs/4_3_structural_queries.md
changes to 4_3_structural_queries.md to include new maintainables from breaking out StructureSet
=> 010-Improve mapping by enhancing the Structure Set artefact #115

v2_1/ws/rest/docs/4_8_metadata_queries.md, v2_1/ws/rest/docs/4_x_metadata_queries.md
new document 4_8_metadata_queries.md
=> 002-Support reference metadata #46

v2_1/ws/rest/docs/4_3_structural_queries.md
Changes made in accordance with the document V2b of feature 012 Referencing of hierarchical codelists
=> cr-116 added hierarchyassociation, replace hierarchicalcodelist with hierarchy

v2_1/ws/rest/docs/4_3_structural_queries.md, v2_1/ws/rest/src/sdmx-rest.yaml
I have now made the changes to the Open API definition.
A good way to review these changes is by opening the yaml file, in an editor that supports Swagger / Open API. On my side, I use VS Code, with the _Open API (Swagger) Editor_.
=> Change Open API 

doc/content_negotiation.md
=> Add info about using semver in version string

doc/content_negotiation.md, doc/extend.md
=> Content-Negotiation vs. query parameters

api/sdmx-rest.yaml, doc/registration.md
as specified https://github.com/sdmx-twg/twg/blob/rest-71/design/restapi_71_design.rst
=> added support for data registration queries

doc/metadata.md
=> Fix typo in documentation

api/sdmx-rest.yaml, doc/schema.md
=> Add option to generate a schema for deletion messages

api/sdmx-rest.yaml
=> Add 204 and 422 status codes

doc/content_negotiation.md, doc/index.md, doc/registration.md
Close #242 
Close #241 
Close #240
Close #238
=> Fix issues affecting the documentation of registry queries

doc/availability.md, doc/data.md
=> Encode brackets

doc/querying_versions.md
=> Fix broken link in the documentation

doc/data.md
Added details on how time functions can support vintages
=> Added vintages section
